apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: ai-task-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: omkark158/ai-task-worker:625e758dce45f2987fdfdf5951c7889a9efc41d9
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import redis, os; r = redis.Redis(host=os.getenv('REDIS_HOST'), port=int(os.getenv('REDIS_PORT')), password=os.getenv('REDIS_PASSWORD'), ssl=True); r.ping()"
            initialDelaySeconds: 15
            periodSeconds: 30