apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ai-task-platform
type: Opaque
stringData:
  MONGO_URI: "mongodb://omkarkulkarni923_db_user:LtM7jEb3NyTkiXgd@ac-t2j49iv-shard-00-00.cv9ehpg.mongodb.net:27017,ac-t2j49iv-shard-00-01.cv9ehpg.mongodb.net:27017,ac-t2j49iv-shard-00-02.cv9ehpg.mongodb.net:27017/aitasksDB?ssl=true&replicaSet=atlas-barmmk-shard-0&authSource=admin&appName=Cluster0"
  JWT_SECRET: "Omkar@15"
  REDIS_PASSWORD: "gQAAAAAAAc3SAAIgcDFjNzU4NDQ0NzlhMjA0OTM1OTFiODhmMzA4MjBmMjk3NQ"