apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ai-task-platform
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL29ta2Fya3Vsa2Fybmk5MjNfZGJfdXNlcjo5M1BoYzdYWjhrQjRGT3U1QGFjLXQyajQ5aXYtc2hhcmQtMDAtMDAuY3Y5ZWhwZy5tb25nb2RiLm5ldDoyNzAxNyxhYy10Mmo0OWl2LXNoYXJkLTAwLTAxLmN2OWVocGcubW9uZ29kYi5uZXQ6MjcwMTcsYWMtdDJqNDlpdi1zaGFyZC0wMC0wMi5jdjllaHBnLm1vbmdvZGIubmV0OjI3MDE3L2FpdGFza3NEQj9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWF0bGFzLWJhcm1tay1zaGFyZC0wJmF1dGhTb3VyY2U9YWRtaW4mYXBwTmFtZT1DbHVzdGVyMA==
  JWT_SECRET: T21rYXJAMTU=
  REDIS_PASSWORD: Z1FBQUFBQUFBYzNTQUFJZ2NERmpOelU0TkRRME56bGhNakEwT1RNMU9URmlPRGhtTXpBNE1qQm1NamszTlE=